---
- name: ensure nfs packages are installed
  apt:
    name: nfs-common
    state: present
- name: check if mount directory exists
  file:
    path: "{{ nfs_client_mnt_point }}"
    state: directory

- name: mount the filesystem
  mount:
    path: "{{ nfs_client_mnt_point}}"
    src: "{{ nfs_server_hostname }}:{{ nfs_export }}"
    fstype: nfs
    state: mounted
