---
- name: install nfs-server packages
  apt:
    name: nfs-kernel-server
    state: present

- name: ensure exported path exists
  file:
    path: "{{ nfs_export }}"
    state: directory
    mode: a+rw

- block:
    - name: create filesystem on disk
      filesystem:
        fstype: "{{ nfs_fstype }}"
        dev: "{{ nfs_disk_location }}"
    - name: mount filesystem
      mount:
        path: "{{ nfs_export }}"
        src: "{{ nfs_disk_location }}"
        fstype: "{{ nfs_fstype }}"
        state: mounted
    - name: grow xfs filesystem to the maximum size
      command: "xfs_growfs {{ nfs_export }}"
      when: nfs_fstype == 'xfs'
    - name: grow ext filesystem to the maximum size
      command: "resize2fs {{ nfs_disk_location }}"
      when: nfs_fstype == 'ext4'
  when: nfs_disk_location is not none

- name: update exports file
  lineinfile:
    path: /etc/exports
    regexp: "{{ nfs_export }}"
    line: "{{ nfs_export }}   {{ nfs_export_subnet }}({{ nfs_export_options }})"
  notify: re-export filesystem

- name: ensure nfs service is running
  service:
    name: nfs-server
    state: started
    enabled: yes

- name: flush handlers
  meta: flush_handlers
